version: '3'

services:

  db:
    image: postgres:17
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}


  api:
    container_name: template_api_rest_fastapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=db # Indica el host dentro del entorno docker


volumes:
  app-db-data:
