name: ci

on:
  push:
    branches:
      - develop
      - 'feature/**'

  pull_request:
    branches: [ develop, main ]

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run API tests
        run: uv run pytest tests/api/

      - name: Run Repository tests
        run: uv run pytest tests/repository/